### ISSUE TITLE
Can a consumer also be a producer and vice versa?

### ISSUE THREAD

**Issue by benjis** [edisonywh/rocketman#14]
Had a quick play. I think it is a common use case to allow a consumer to emit new events and to allow a producer to listen for certain events. Do we plan to support this?

**Comment by edisonywh** [comment]
👋Hey @benjis! It sure can, what have you tried that it doesn't work? I whipped up a quick test and this works:

```ruby

  describe "Hybrid (Producer + Consumer)" do
    it 'should be able to emit and receive message' do
      Hybrid = Class.new

      acknowledged = 0

      Hybrid.class_eval do
        include Rocketman::Producer
        extend Rocketman::Consumer

        on_event :hello do
          acknowledged += 1
        end

        def produce
          emit :hello
        end
      end

      expect { Hybrid.new.produce }.to change { acknowledged }.from(0).to(1)
    end
  end
```

**Comment by benjis** [comment]
Hi @edisonywh, my apologies. I wasn't clear enough about the use case I mentioned. 

What you provided works already. That is to allow a hybrid class to publish/emit and listen to it's own messages.  

What I was thinking is more like to allow a hybrid class to emit a new message within `on_event` block: 
```ruby
  describe "Hybrid (Producer + Consumer)" do
    it 'should be able to emit and receive messages' do
      Hybrid = Class.new

      acknowledged = 0

      Hybrid.class_eval do
        include Rocketman::Producer
        extend Rocketman::Consumer

        on_event :hello do
          acknowledged += 1
          emit :ahoy
        end

        on_event :ahoy do
          acknowledged += 1
        end

        def produce
          emit :hello
        end
      end

      expect { Hybrid.new.produce }.to change { acknowledged }.from(0).to(2)
    end
  end
```

At the moment this will raise `NoMethodError: undefined method 'emit' for Hybrid:Class`.

**Comment by edisonywh** [comment]
Oh, that is definitely possible.

The reason that it's not working right now is because inside the block of `on_event`, the context of `self` refers to the class itself, not an instance, whereas `emit` is an `instance_method`.

To make this work, just do the following:

```diff
- include Rocketman::Producer
+ extend Rocketman::Producer
```

Do you want to update the README to reflect this? I'll be happy to merge that. Thanks for raising this :)

**Comment by benjis** [comment]
@edisonywh, thanks for looking into it. To get the above spec passes, I think Hybrid class may have to `include` and `extend` `Rocketman::Producer`. Happy to update the README file to reflect this.
